service: ieam-serverless

# Add the serverless-webpack plugin
plugins:
  - serverless-plugin-typescript
  - serverless-offline

custom:
  serverless-offline:
    noPrependStageInUrl: true

provider:
  name: aws
  runtime: nodejs12.x

functions:
  ieam:
    handler: src/ieam.handler
    events:
      - http:
          method: post
          path: /
