FROM amd64/alpine:latest

RUN apk --no-cache --update add jq curl bash nodejs-current npm procps

WORKDIR /server

COPY config /server
COPY lib /server
COPY *.js /server
COPY package.json /server

RUN npm install -g npm

CMD ["npm", "start"]
