FROM alpine:3.10

RUN apk --no-cache --update add curl bash nodejs-current npm procps

WORKDIR /server

COPY config /server
COPY lib /server
COPY *.js /server
COPY package.json /server

RUN npm install -g npm

CMD ["npm", "start"]
